# Generated by Django 5.2.5 on 2025-09-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tip_type', models.CharField(choices=[('food', 'Food & Nutrition'), ('remedies', 'Remedies'), ('disease', 'Disease & Health Awareness'), ('other', 'Other')], max_length=50)),
                ('other_text', models.CharField(blank=True, max_length=200, null=True)),
                ('tip_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
