# Generated by Django 5.2.5 on 2025-09-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0001_initial'),
        ('volunteerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuerequest',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rescues', to='volunteerapp.volunteer'),
        ),
    ]
