# Generated by Django 5.2.5 on 2025-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='online_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Card', 'Credit/Debit Card')], max_length=10, null=True),
        ),
    ]
