# Generated by Django 5.2.5 on 2025-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('volunteer_type', models.CharField(choices=[('Street Rescuer', 'Street Rescuer'), ('Adoption Support', 'Adoption Support'), ('Bird Rescuer', 'Bird Rescuer'), ('Feeding Volunteer', 'Feeding Volunteer'), ('Medical Support', 'Medical Support'), ('Community Educator', 'Community Educator'), ('Pet Caretaker', 'Pet Caretaker')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True)),
            ],
        ),
    ]
