# Generated by Django 5.2.5 on 2025-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0002_volunteer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerGroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('group', models.CharField(choices=[('street_feeding', 'Street Feeding Crew'), ('bird_rescue', 'Bird Rescue Team'), ('adoption_support', 'Adoption Support Squad')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
